title: ~🌼~
  
remote_theme: jekyll/minima

# Link pages
header_pages:
  - about.md
  - projects.md

# Layout
show_excerpts: true

# Display footer with links external: 
 - {title: Github, icon: github, url: "https://github.com/cshiyun"}

