title: ~ Shiyun ~
author:
  email: https://github.com/sycsy
  
remote_theme: jekyll/minima

# Link pages
header_pages:
  - about.md
  - data.md
  - digital.md


social_links:
  - { platform: github, user_url: "https://github.com/sycsy" }
