title: ~ Shiyun ~
remote_theme: jekyll/minima

# Link pages
header_pages:
  - about.md
  - data.md
  - digital.md


external:
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}

